# Deploy Railguard contracts to local Anvil and print addresses for SignGate env.
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$forge = "$env:USERPROFILE\.foundry\bin\forge.exe"
if (-not (Test-Path $forge)) { $forge = "forge" }

$rpc = if ($env:RPC_URL) { $env:RPC_URL } else { "http://localhost:8545" }

# Anvil default account #0 — override any stale host env that points at an unfunded key.
$AnvilOwnerKey = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
$env:DEPLOYER_PRIVATE_KEY = $AnvilOwnerKey

Write-Host "==> Deploying to $rpc"
Push-Location "$root\contracts"
$output = & $forge script script/DeployLocal.s.sol:DeployLocal --rpc-url $rpc --broadcast --private-key $AnvilOwnerKey 2>&1 | Out-String
Write-Host $output
Pop-Location

function Set-DeployVar($name, $pattern) {
  if ($output -match $pattern) {
    Set-Item -Path "env:$name" -Value $Matches[1]
    Write-Host "$name=$($Matches[1])"
  } else {
    throw "deploy output missing $name"
  }
}

Set-DeployVar "ADAPTER_ADDRESS" "ADAPTER_ADDRESS=\s*(0x[a-fA-F0-9]{40})"
Set-DeployVar "HOOK_ADDRESS" "HOOK_ADDRESS=\s*(0x[a-fA-F0-9]{40})"
Set-DeployVar "USDC_ADDRESS" "USDC_ADDRESS=\s*(0x[a-fA-F0-9]{40})"
Set-DeployVar "ACCOUNT_OWNER" "ACCOUNT_OWNER=\s*(0x[a-fA-F0-9]{40})"
Set-DeployVar "RAILGUARD_SIGNER" "RAILGUARD_SIGNER=\s*(0x[a-fA-F0-9]{40})"

$envFile = Join-Path $root ".env.local"
@"
# Generated by scripts/deploy-anvil.ps1
RPC_URL=$rpc
CHAIN_ID=84532
ADAPTER_ADDRESS=$($env:ADAPTER_ADDRESS)
HOOK_ADDRESS=$($env:HOOK_ADDRESS)
USDC_ADDRESS=$($env:USDC_ADDRESS)
ACCOUNT_OWNER=$($env:ACCOUNT_OWNER)
RAILGUARD_SIGNER=$($env:RAILGUARD_SIGNER)
SIGNGATE_API_KEY=dev-local-signgate-key
"@ | Set-Content -Encoding utf8 $envFile
Write-Host "Wrote $envFile"
